---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: proxmox-csi-config
  namespace: proxmox-csi
spec:
  encryptedData:
    config.yaml: AgBk8rpPq1q/7Skdi4ItPko9QnWwOBQThWtMdQMUq5uDh4KoCi9Paypxp6X+MNTMeN2wiB6yco3eYswoOMtTFm2cY0W+E025azGK0v0vJ2j1Obx19cXY1waodrbePWvXBL1JiJI4wHvCxbBXamVjuaS4tC+oyLDeackTixiqnTw7ZirzRqKt/6iRsXUhoS4qC9unFNrUW2/NdSdS/UP+wOQ5MeHEMWTfbzr8D8gpVk8Es/OmEUZHbCIQB/aEcasU379HnkJPy8zSn4r5kj0lxh1BXdDyJs4yLTxyGVg7v00NPhHpjln76YHbrxtwhLKxPLjrV1o0zGydtcJK5ZYP5P+8dSfG7P54/iFVDhPjfDFa0H79804xLR8WG/z854V8VMbe/FmfqnGuaqX8YW21uiOol9LGsOIR8eADLxWYTYARNWdMlYWn24FM14FPhOpSvT/XyznaisXTNejVEYC0NpytPD2dIYNhm1sPgXGtYXpAVMxU4aXzWffpfXgb8OC1yKIHHe5g5MHWhIcCg4mPildlZPBKOkWkka58x9oK8FgMG1919gzzuV/bULg2WjxSleIWRns+NRfKOKfGjMEfL8nRsDEC1Tvreot+zZamrsb96GinbKeMXhUlMQYn614nZnBeRWPEaijbkLJSWOIFq8dkIqFdYKJXQBVZyMrGxvQSlPrtAl6ACgkGP8DJgZOR+g/xlcqxduw312NqmZi1kbA+AO+YOczfqvn3k0gmFIJ3PiT05HOMaNSwsVChJ/d7jrzz+ywJiTnqNYmU+6/sJss9M/dcnABMsI58VrOePSo+t97RS4f0ZhROYjQDcVOdkXph5l6wEQe7JYgT3J2rrAXPClQsi9x4HU0AOH7YYi3tT/0BZM5qh8GoTSJiVDY2tur5sjxCz44T2NSHT5ibHVMcwt0LZ2bHGpl7syT52kK+M51I0cB96H3sjHUcTnyKmuTJshLIzgXCHlWvoKpyxTA=
  template:
    metadata:
      creationTimestamp: null
      name: proxmox-csi-config
      namespace: proxmox-csi
