---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: proxmox-csi-config
  namespace: proxmox-csi
spec:
  encryptedData:
    config.yaml: AgA1NefQTW3Bs6rzq9SyxFBAg6xLjo/+CaFZriec/vYTkTJyeMvXzcnQQM+2xc7gbDrEBM/hcHzX9DeNkhPV1x7Z4taX0zBrhvo1zwxliET/AlXx3zpTH1pRuXhE06dsdNCR7d3jc5Ab/ox2kgM4bNfOx+WYULkxGtVX9fM1Z7h5wjEBp1506YytBdXiJOHN3j+8qWwOUc6WEeJRuPmI7n73Rr3pjAYE/mAjZN4l1/Edh4QmhV9rxA0lHVPgtP7wSCmGfIvX2U3xMNkirNFwpPnBNayhsRYR+8sYX05iC90AyC03LX2vVLhu9N7CxlRNtE1xgluHfcTh45OdHD9SipHuR4LaOoUhSLiTwE8QwKVEVnWKSOlf/O3bSsySyYbrkuKs582PfbQ5QtQFRNaHMSAWULqPt6r1+RxPcG0wOaBml9j/Q6WPorI/TgLudEqWuxphud3TqVCKkF3IpHPKVZessdG7+io5lIDqJn1OpeB3GF9xRdkkshTMR2QtFsPZWEmXKAFDADPcg7Q9uDX3bLrzRoW02aw9ZLQUhqa265zQLazFT51iZKj4FGqebxiWkmcVcGZMR/0iedl+DUJ+MhcDhFt9MQhhk72y2KbewWs/it+bfuxWFkqo7XRmWvu+qxmv0rJDP/N0L2c7db7xQ2Qrx5nLFJX7E7aHuC/FKeTegqCCjA7NvgQCr5XOYTQZ3V4OC6AmAIflhtevsXi04jIsVvoBy6ay4zH19SAxK+d6icCWYY/VTBiFf8aCsF5QpTzFgDsgwX3DKrMww9DNtRuXkoAK9xcPd7rykk+e1AVzJEWGlz+/bNYX0UFKk9Orgq+ARZXQ3HKHMTckLmC2s8pdffvSR+Tqgl2NsBL4l4AiS1zIcaFUWZ4XgBZQVFKst5k1n6I1+MA2lAeJUVF879dkwEoYsY/iTFpaDMEMehY2C3qx1y9fzD33zNerSYvp+0YqOrETMdQauWUFTHAaMRs=
  template:
    metadata:
      creationTimestamp: null
      name: proxmox-csi-config
      namespace: proxmox-csi
