---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: proxmox-csi-config
  namespace: proxmox-csi
spec:
  encryptedData:
    config.yaml: AgAGJkQII10c3/3gjtQOxF2C9E39kwpjBKGK5jAH1FmPM1L4QsM+NDzmcm75e1bHo7d/l9KpbSVA3qs474MhOT+fZ6Dhs/WEFeuZNuifqPe5irakmfzoRtgqDTnK1lhGgaLZLuquyQ61jmW21JZywYZLCyuIvFSvQp/A0PKwpRtUrvS9vZoGQCcOfnKA5FSV4ntGnGA1q2O2338EDfE8DhtEZaY/4pXyz5zvGHhjwR5EcejsupEsrgpnYbgP/dprPzs5+497XyYf5ycZmw3vZXUCHBnPsS97TSsEZEEnbVJwRIg6cHIQWgeLhq98aMTTEC4LIif/0LjnCE0qPRx5oW7Kb/og6+ytwrBtuAPCTDwG+3e/PP81k/p435eTbal/cqEAqOaMvlOw9mK6+whbo2Y7T6Mmu7WrxNrprAZbNY8fvhzzpK1+4XKnlnRIKtADlP24+SLykTr5WtnDtIleL++0j5S+TWSp1EH8UZbBQzENO3dRy+lgfTUeZE38uOZnDwMGWpD4GlADZw3H+bKi0rm4cy2dee8HLhCMEEQGct/xaogZl75X23ssS2p8h3P0gQmdp8DuM3TRIn3FDGa/5aLc+YmA7hfTMwg5fzczMqjGzO25Eb0rCGrEjjBu6pQCHr1Y4Eo8aGqp7/xaXhqk0JikBjXDJlI7c6ZceUL3gyev47EF+Fq7sk2CbxtQHEdvHiQViYy+CQi72M7O8oNUX1RZhoyUrDFXV18z4IQdub5AOn9hkFA3bRX4p+wtWPERNwz5xpLqoSkCkjvuk5ydQgqT5vbISDGGvZBqkVno13XQ9DkDuOifuq26/H/9I7KTEkFKhUMuDGOmy0WFQoXLEyt/vkP6JwJuv76fftelM5aL2ZnbmnlOk10haj7Zu1rGQth02V1ZAthSzMI2ULn33vnnRokHa9NJMn9S2cYDvr9GPATaY4R3dPUnvibcio0jSszwB02IzokweBo+rjtYtvw=
  template:
    metadata:
      creationTimestamp: null
      name: proxmox-csi-config
      namespace: proxmox-csi
