#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: "organizr"
#  namespace: argocd
#spec:
#  project: "mediaserver"
#  source:
#    repoURL: "https://github.com/enrico-laboratory/homelab"
#    targetRevision: HEAD
#    path: "k8s/mediaserver/organizr"
#  destination:
#    server: https://kubernetes.default.svc
#    namespace: "mediaserver"
#  syncPolicy:
#    automated:
#      selfHeal: true