apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: "ai"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for the AI workloads
  sourceRepos:
    - 'https://github.com/enrico-laboratory/homelabV2'
  destinations:
    - namespace: "ai"
      server: https://kubernetes.default.svc
    - namespace: 'ai-*'
      server: https://kubernetes.default.svc
