apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: "ai"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for the AI workloads
  sourceRepos:
    - '*'
  clusterResourceWhitelist:
    - group: ''
      kind: PersistentVolume
  destinations:
    - namespace: "ai"
      server: https://kubernetes.default.svc
    - namespace: 'ai-*'
      server: https://kubernetes.default.svc
