---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: proxmox-csi-config
  namespace: kube-system
spec:
  encryptedData:
    config.yaml: AgAvWNQc5W1rxgfFoXT1VkwVToyfsVtSKrYCVYgM8tsBElG/mtdFpOTHxjDDHpfN/wk6llC35eReH8VEXy6SiZ1z6l+mmV6rCplAEtpIVAjj6L6bp948V5abp6wIdaHxO+PaymAStP4sRtsreKndUFtFl0Z4pEOfsAkaz/9tbNOkhepDNUK/qvODuii+faeGA4ceMwfczQCv1A27ov87C80P6n/W19Uc1QphQlk4cTfOEDCuQlmz8G8xssmY9uVbRwZr+IzVwvWt1DZ3MzNDFCnzJ4Xlrf8MDuM+GdXkpKali06Ii/bwFU0zTojsBVf2BhM7azCcg1ZkTnY3i2wVF1ZVmihq8Df40ZQYYzE3fJnnXxdGah7eAzLkMrMTbf/RVlUcMg5fFlsHwNVOA00AU1y8d5jy7AQzoDhviBXXoAJC6jWuk8CRDjiC+AHS7WCqmi6Iw6nxXj0Lsdx0L89hxSSM+vb0tvYDgz5XRhahqVEku/9R5/HBNv6RfhAC5JNpLz1gSlwTcRxmEV8j9blzmLL+NcO86CO8lClzzctrKx4S98QI1R2T65hwDltKRLCBhWZgUDn0cxUH6U2aTIv6WT9FSne4g9OgZgv8Cku7MKAl+c8NnD6opYzSvK0qJAWKlczeGk5pnYZqQpHS2H8HB7PhPJoxBcPztM0v21U34whsF9ZxwOENQLmX61aC17K8iiFIDJu65tR29zrH4XjwSxUrmvHpsEpLbE+o3GcKhsRcWKM7ovqbi7yurHMTooe1mahKXmiNnuBYyY9OiTsQp4Nyc+mfy9vrWy6LtxAKee6BRGqKtuAZQ7WCqENwXYnKt5chJsfRd2ulrGWkwNC1pHQIgTS3SFYm5ujDRkgsew81RJ0ZeXUtOVo8NCCHIcEOEb5wkQMJ0Uw6ethymeKrOFt1aozjAHI7O5Z0tNN6WSaEKNfkwHu3j+Rayrbb3t4vOLX0ki8PmpdXHZw2fNAdyNw=
  template:
    metadata:
      creationTimestamp: null
      name: proxmox-csi-config
      namespace: kube-system
