---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: proxmox-csi-config
  namespace: kube-system
spec:
  encryptedData:
    config.yaml: AgAFK+n4wv/OZk4tb18Lrwd1i2j5DDXpwXLDexKDo7qS20DPpwim8L8Fa16evYE7tKmWRc+Hkr8uUWBlyrqT9qVHMEIDhHqvtf3EG1XHqlL6APbYLGttQIVPu/1CzRHjdVgmIE4b1kFMIkTH2M5VjA/KDlHZTy9NhUpfWypOn/AmGW2qtFRxtOJeHwjzhkGlQnpLcJbfO6jSZ5uM3erPDKZdQj3RdSNckwHdLA5k5Q6XDao+cKDQDqjbfItplFRSf7HHKgvDHZmcjAZh54HlIfl+9bRpe2AcHcxiuh/TGtEA4y6LUQiBJaEfJSKgLQ1XjWF2X9p8zbZixE7Qh47CmZVE8n0MiDr4trxvtA9/heB7yEsjHpE8PUGGrVPOg9wL7QjM5+z6KMY0zNzEdEoXOBCSTVZcRp8pKSYL69TXxVYRdnZGxU7zjU/QDyJ4NzJtOKXyKsNRu28V+RZNdy7hLON63ROz4EDBQ3r1Qfl6OPBslfvpJRvQlw/DfsLKjp46xtVu8v58FC4mqvrNoN3IZ1X+UDpXmJIT4RRPdyu87zu9SZ/fSW+dL7Gd/8KZ8bo5ipBT8vPKEXYNTxUoTrdqNips6hcALegXI+40jUGTnh6kubvy0Qb3VZut+P+bIWX0/zFjrprK8m6YXEnVpBFNCr8Iaum+SB4NzoSd/XjsntEipKv3bg6XR8d7Wi1h4mqPdxxrHE2WtNAwce9pX8loJblnL4IQQR/LpaH8hPuDBhqc0y1tsQttML7BupsZSy6uqY9YavLNf+FjLVeYnnoriPpa0d0A46GjDmJ/UqSzo39U6GawYLnhyPILHASGVCtlzOVwhiTvIoterDYp7relbyvQnBDZ5mEhoAu2exSIpL5nmpuY5LTonel6btm5DNaVFdfV4vPv21FyIwqaOWt20I+ANPpnuzcnnQtKhZLIwTZT4Fl4IKXbbGMeguzmnZuGwN/HR2v4VT4f5KvdW/jrnXA=
  template:
    metadata:
      creationTimestamp: null
      name: proxmox-csi-config
      namespace: kube-system
