---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: proxmox-csi-config
  namespace: default
spec:
  encryptedData:
    config.yaml: AgBgkcdIQmDrMvNKmlElDvbleP7r5zXvKQP2r9DAPi8Fv6LJEHkWOpI84/NrzNzGMRhzkDqETgRSMdRSdGoYAgbBa+Abi2quN9kzoXdVFvn016aj0rnyGE3ADfb1AOcLOSIRgh1r1iziIemHCJqX+tBD1w4+Brh+nWBFfvKIndSsLlnQICOvFrEkCnJcy0e8B1sTC2Nya7swQxqoMgiLN5VC6oOm7G93Ck9XQhJ9EA9UGoz5jkKK10f8B1y6sKyQfRIBHZr8DyS+mHtDSsaECC6fA1irtMBFeDbWIS+dbu7Dx+SfyA2R0lf01kMK3XKwCuKJN7uRVSpmb9onkQeho+UXWYcTCPBpLHP/ZEvAOlCOmoNreOSDCCXFJYKU/V0EF1C2EgNCRPodlJNX2i13XyusFZKpbN+IQq7s1HhM0O+RiQeGml7bBFgszhDTrmKE6DPhdpgN0NWTBpj7JNBR4wiifojJKZVG/x5PzSWUv59KKSs9CIK6pe4L6msydMqib0UWY8wLXf8zDL+XOdDhU2Ubamb5WCAr4Pz0bvSMu6Dblmdr/FqcwFFeuzK0QOiKqQALh/2+xeSXHjZhE020ehwt8yiASIjw7lKg4v4zzfR4+nJsvB2vznixw8aOTMb8nDd5r4PVzMouA9klkqEKSKvDzYh+ZerU0549NeKdEEruGYPqpKEs6MpfcM5+d9rreI5hgrC0sDwB6G273+uK20cOQdUUkqmtymJoGbJyqnxTXA++eTTD+F5fhJcNCNbQBnnUWGK7zMUEfzSnElt/x0NHaAAoZVypQ+//p0Rc8wWu6fduhPCLLSBI3N5IP4t+47NCa5vi3E73Z1B46NCGUj/u9qxeIJ7pxOsVJYikqvpkf2OKfQ/zB5yD9v9ESdW6Rquc6PTC5jycQqjfZQWbp+4wMKQHbpZSxj84GKAMdE9pWyXfdWrK1qR0pOKLeIoEwzSZ90ATbQvznMcip8swPD0=
  template:
    metadata:
      creationTimestamp: null
      name: proxmox-csi-config
      namespace: default
