---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: proxmox-csi-config
  namespace: kube-system
spec:
  encryptedData:
    config.yaml: AgC6Fb+NulSz2h88ej0x1JVFen12g7QTrFlhpA/tAKOft0twI71c3F1Azhq8aHiHiJYOfBYh+lvRyBU7A2VPJPihzFLie9O1HZJD+d2e+H55YauqzKM+lm8LtsSzmY6/sRVyUZkqTz6X/dTYg/14Zg++FsWCafZHV62XeJAh/3ylvD9O1lTguNtLUK15iT5AoZ+q0xzX9CKOHXGU+mwV8J0z+0p6b7z6cbzoWz6Kw4rC8cwqBmnU3oyiojxkbaDrv0/JsDyQF4Bi0ioOydu2NMwnLFPVVrwd2eQwv6133FKWRBAF/G/eIPcz/1k3270nIDrag/tyhtrbsO6/M4T21Jbiw5IRekIT7qPLJbjYdEAuqIalHxtEO3udErglEYFE0I8dQyaEFy8fJbd3TG/ySvqsZxEkILr+L3Ju3yhDVv+0thb9n0Ot1FyaUwk/hMPk6UR96DZsH2BIkZER7+UrwPacbMKgkBwXnygiM5fNCZvkVL4gax6lf6y4MO7xEC6/ihvryrF+9hqb9Hg1vIc1kNoLEQ0r8dKPxgYiAnToa/M8aK83IHz2M3fL3eeMZvUa+yrxmC+XSdCCez5tBcZMpJMwRd1HEDybB7VvNYUp4gkZOwJWETtYqMcadvzDEzApXfqg7+YlPYCreBoBHxpH0VUFNhlBAoKupD9qjRagq5GAi3e2ZVeTEbYzDfVAug6KYQB+6XqZ2lOubpbRJ3xVAvvENVPYwgY5jGLKtFL3yhYO7I9Hl7qHiyR/Rc4iCQt6POS5WJnkd6e9TR70ZCsnvg4A8xszFNkSKH/iQ2BvZlmSayzRw/bm8O1XbtUnhT1AnstqzHIfbdGSzpz7JF/3WhMhwr8upHCmm9XGFWVXp3g31I6Sfjr+KuCNb6rU+S0cKSynqxB6uH7fq9cKNZ4TmEzMrPZtK3iA1F/yAE3llEjvrvS5L2iEbqEEwpc8Ljz/haDiCIKd+YhdFmJOBjP6JF0=
  template:
    metadata:
      creationTimestamp: null
      name: proxmox-csi-config
      namespace: kube-system
