---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: transmission-secrets
  namespace: mediaserver
spec:
  encryptedData:
    pass: AgCE3R1j6isAiXc8bW8JZzETAT/meLuYbagyzc6HRrIbrQguuUyCwDESzS3oYsC9uHaAGbM+SBIoKgeQxSmIMvGdEeHcjtCxS55KerrUfs1riGuSNs+WUliDSVgOEzmEKAaKPrFf1UdTDkOnD7r7eCE1LpcbdCGROPXz4fqaxIKrokgK0+FmrCYzwdKfLSUWp9EHgcshjLVPq5oCCbPJQMteVzoFbCz1JnrB0bE/TBRJbKTCZRjjHh++GH7qyrkDuoB1GErTsT/s7O4jpwMGenXgMJEv9DGL5V5SnYzWg7VtsQhn3ypiRnszp9NS5mlrZn+2YEiyrZ1gfyTPxdRmMNTgU0JR/iH3y3F/n8majI0Guo7s2Ls6z6xafO6OsPxJ6I5wRMelGVCUjeZ5GZytx1qgg2lT4zHWtCnkXpDZje9v1u/TIgsO3R0VSGBiG8USXZZNeBdeBnRblzHlar91YUegS1G/7YU9ton1ltUtf8dUOV6vluX2+2nbx2H8RzXCQLpOyy+Ng2C44iMpKdNBLFPw+WxCQc1e3Wus7VFLGcgKcg+FV5ZoEeOqno02Dh/9Cs4Pl5+vaeem+RejDgwLnoKcIxliSUfqog3hwU3BfTaod/g8aBUa6LoNH56Rmr3m0Nhy2vEUV23N11CQ++kHnKRoOcaHCh6aSdmNOfEpr4EMCLnVEd0kQKVKyOwEPRFvVqFBtnSRCrmmCw==
    user: AgAO4h5k5og0J1ipS0fzjwBmAzTQY83xQgAu9gku3UHLk5cZu59n4KaFzBwKt7oT/deplFI588YQJ0Js1xYJyUwUguBbqjVNHUuczkfVScv9gFviy/tHx9B4tvXI9rM2IYxvfa5lOI0S10ihoMmD2KlCz2vozP9KLxqsO8e+fRUXb21FK83RtTcllj/K6ckuOyoURQ93WxWvvFvH18CMMaw5VEHPrZq/cppsgE9MVCSAmRHRUDTSMyspCIwTUovxfJo78rSdQet+4ORraT10dHlClYPUXnOFn/2iC0Id6/kGpqjLSWzu62AllK7mEIuvhrwtjIxntbQQ8LXqj7H8hhDzyMNdribEsPwEfT6f1Ix+EVCzmxKLAcbrjEPXw+SLc8ssxj0r2lITUujXbycfykc9yn6ijhDU3geGzFn4b3JlveOYezPP5NFjpS2Dx8BK82SvnfcQpvMJIOYr25cRvJ8R1aa9+1QgRB4srnweEOP+e9UibT0VWdrZQLoDEDi53hj4OhEMMhInoz7MYlbbOZvD+Pbl97oIlPCoz/q1IcAup8xr/WfrH+s3qBK+/ghLoT/0MzeB0QmfKXC1LlLAdQm4QOq2Mj7Lz76l/mqO+noEIKTiSeo8fMmERLQLoQOgFxh64frKm3Q7XF8sYMpN8UnRznn+p//B+IHIa7WZA5FOptdyZ2FCEh3PBM0Mp6Db19yUK+jzDQ==
  template:
    metadata:
      creationTimestamp: null
      name: transmission-secrets
      namespace: mediaserver
    type: Opaque
