---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: transmission-secrets
  namespace: mediaserver
spec:
  encryptedData:
    pass: AgBs2e+Ox9tUFYR04h6kBtE9AeJnsEar7CkmVV5/FU2Z86slK+2JTV/pwx5j3XOm+5ogo6cBd0+jIU7rJNkbHa2oPZv+nGwtE3BXV6Z8Aar/wH25o31MYuS88nkDx3z19lLaCRwrLlH/rK++Inec+W9/0J5sK6kUQOwteEPC1gkh/UZX1I4pQsTNRH+2aaYpcYgeW+1zyKsvTxk4b70kIBwnrJWy2kIqoXgnoB4m6/TNRxKjErTv5TMPi0k+aHHOVEC8Z3boED9KclY9ZeZ4znqjlF7n7oM4ltFN24dKai6uVdHKsjYWuOswGdpCFdDbwvNdLsdy4fnlL9Oh+qhYCc3zoqvizvbB5EsRnRqeGAYiWFw5ebaLzLq92wZZD8810MalO2oalIMt/nAtUaXI5J6GbJ0ZK6DndYuXC4tYGvJSo28GxXsGj1LQIKp3GRWwlxe4Bgdnf8nhtVmxQVsEaWvwSvt9IytkxYvArNL/KgNG2fQk3zp6Vcz0dmURSKQWOmdOq02/NDCkIQwQwLVP5YsnsMosue8nUXyy1n7L6D4KynRzxRhZKAawrTXsa2CJbCIqtSey8l5XpTxXyZvqgWDMd3BWc1KBBZlI3pfVvWg7+BuT+Tvt8SmATF2rlxBdjqMogztMklqDCiT1btjHlIZVegqV17C0EXpwIl33zh8Q6Mu9lsK5XxVETxOpHWznm/qbCFM6ZQRf1Q==
    user: AgAhaNRqMjXVPbdRkIU2OdbQMyPGCmA4MQQPaR0NYOGYfk9Czp+oWwzemhhBkS7OLXRcHc/ZRSWfe42h3Jn7UOdRHBCwl4lEFZDGRmYNfgbrvwL7lFmQlpbC5OZx2JEPGuTwrylPZLJCkKPD758wIjNy/8jnfR9qpMwBWOueW4dud/KaBKApVgSbNEju9ZXGZpmrzuvGSFd5QsFcYsvDU5X+PvcH6wHHyfWjBOPkFhwseIOp5PK8mdlz4Vc32eekkKCRySsHmztLPhy13PAXiWa32zJjbVnKuj1m+tyg20OVofzfwoi0uRr+7acp61UERFxrN5BG9HbEzev/38CMFPq39kDRfIPOjR736rHOUP91IV4Qj1Em3H/tAHuHOJCpNRYI6mUWL/UgRb1zxayuaX6HmRj5fypeFvHUA5qqTuWwlLUY25IwiE1HlEG3/y/y+krBNX4tif6y0GiD9eS1rdAcd+4cq0vCGaA8csNmC6fVO3SoZeNTKEsL5VVb8ky0xYshTy6g4BKwnQA9/o+7jJ9c476fF9R67JsOv5hv9Jigu/Dk7KIU7rJI7iECj1zknwqPABcFTFfHvBH2lvYTvaPVRhl0Ni4CiGvv8e/b1H277qDez9qwCygtxKBJOLnlQ9I0niWjaBJKtPoC1odzx5v5cgJtHe2q8zSmOj+LpsevBZ+RDQsCXLhhp4xbjd4imojx9VE4OQ==
  template:
    metadata:
      creationTimestamp: null
      name: transmission-secrets
      namespace: mediaserver
    type: Opaque
