---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: transmission-secrets
  namespace: mediaserver
spec:
  encryptedData:
    pass: AgCrgYbi7Q0cibZYGz8mmenf+i2ydq0/x9knAe63lMa2Mma7n4fdG3jUN/VxNaS3mZHef/Xbuwyl/hM1zoDt+azHCLBSW/mRCBV4h6kC8TWzLlSot+s0gOXLbVrQLA3nqfc3S85ngeW1/m17PiXrf7m07qyHBjtFDYjlNudNkDuDl+TToW2ii8U6tWdKc4bmsqljT4qKxafK3rDQ/F7sTmJFLh9HJpmoIioNGG9mLKiPv+JoMGJ2ep6qaarRRYYXRcLUOE3ENfS4AZE2zeevFHBalod8vWp8FeUcmBGAjI8up44IK4Q+DR5IOkl3dmMJ2wqvafwA8FkgfnaDqLd6RUh5sAEd9hRf/dI2sMBZcurwmqbh1vglhyuYnVU77xbHB/kI50hYFr1sYwM4WFF0tH6Fy5ZNpkSzSJHyyVwu+eM8+hU8RbMJ+5D7Ri/t2M5/Pi3s9HM+qhq2EZFR+GK+7xgxBWUYWtiGKOpJXeHHo4RL3LqNERxnTHJQzeWmI6Zq16x+kdgRNTNw4x1KBmLtxXiR84Z0zshpgmypkmhhPlHG4SDB7btV91Qyk+/l0XQFYfsCuHvmntX3Me8NnEojzt7nsxEu5rM/2I03MhH8bbmqLLsLANHUgRfYaq34dToVHeuZh3jszRnFGQkDDwSdpRhQYdBGojGoEAHGSNuUyL9Q/FsTdpB6M8inDTLqtx/oWCXJ/dM/eLwnnQ==
    user: AgB41Zsu2ktUY2ePZb7m1qqjFyJYvdWYNs57CzzY3L6YGhFNPvbumjQ9hrYOcyoVa9XBNn3oNZr6j3pZ/VexnSKNTYV5wZefcFb1HyiEYILwp8sbzb0g2dRGGLqTBMjcltSodNGy1cZI3x+EzWIfo4AiH05J5Tzn5tHfH2kGmPV+MYp6Y683JlR3pPjLkHj0xRXg9h2usAG9YXRNg0Jx6rtAt/NzZDxl3L5nNwwIfFi2SsB5QMtc4G/2BA8Qyb3XUyYYqzYhDJEmQmaE2CkT5A2JYTaCSqObVyyeb+ZMSiMAciD1Is8MYAuNy+8sI7Lq04YLpnnEwaF2YJ4B4AS/UtkDjE02IZ4WZgQTn7ApTk23N4JhxONXISZdcKt+SHn0Qt46aIcWQLS/N2waOrj7XHjGbQlZS0nfDohwqZhWLubTf7GEpCTdsbLsHmr6L2dRz3W4L2k1+pP5LZgviorPL1aAc9JR9Uvki4ahKxsSWN/qo9WCnSB2vHNhrPpQ2Vx2bFuAbd6/sL77+2M18r+vlNm2dmUcz7qitOMwEztoRUKIv3QCgRThsPCmWMjSZ153yRj0qbRnwQbInxGzRHVned4KEJZ+GP+SLeZx4zkEkKeNpt9crw6pd8uworIQP4vHpjf1js7AAPVuBYnGZqmMUFS4lO3JbK51WPX1Rn6uw1Kytcn7ent431wB6Mhl+8X1Q+afUl9hiw==
  template:
    metadata:
      creationTimestamp: null
      name: transmission-secrets
      namespace: mediaserver
    type: Opaque
