---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: transmission-secrets
  namespace: mediaserver
spec:
  encryptedData:
    pass: AgChpmV0scuqEmDu6i2DyQQzfU7TuTv+NwWN6IKIZDEiCyhKo00C4hy+0xA4MgSdIv+Xvz7IP55IzRV0l78khh+0JXZrEdGmBVXlREx5uPzMIQ0iklSJqS5+vTpL3PZR8Yky1shi05rX9szktFLRMxLsYTHEKHUSvi6WlTvN3TP/ORm0oj+RqsX/K7AfSR/eR8L6WHfV4wPdd1+1BrDMiM0hLEZ31l35FXuY828LS6yKJttPzFYAc+b+IxAj2UIWDb9gd9Fw9A6Q5CvtaKqk+JlwRWu/uNMBhriOWJFYh0GboQu+g4JBtmrdziiJ85+5yeF4jFWMkC1UHnqq/cPlW9AAXl162PKsf6gvsvcUsFC/t7tMWZPaYDEGNnRXgEfPx90bhVDxFvi8YUc/0cDOy4jMiQ96mtggTSUSv5gRBHNabRUoFyGcd7iQPToLNEAv0ow7qqTp1Lu5mWj3uT/j0lGpdXk6I5oovftAqYjmxLsBpMyFjmzJcn5X95lBMAQ221w9VVPWl9SHVJ21KIcWL7123UvCSInmlHeON1su43RWxTpf7u/Rp+BAUAHP+sXpGbvvskb2/HqAZ75qYFXOBhWd8ibCFBfBAw33B7BprFesD9s63gEh+ALReH9coEAHTBfOPllBMd3qX3s6WZ70AT1KV8DFpXrefuAMmqRKeEXraroiqrbv6xl5wcEtzz1owX54omT+BubJkg==
    user: AgA5J9uoUoUXpX1W+w+KhBXyOW36uXJmhCD+U4/Tssl9wiCM91YnHrRYSBzOdoTnhI/cFERrqlJ2gTaOzH6qxRaeNQNhdvOjaeplJH4XR+N6bqiZOsJav+EDP60nAtXZLJlfPdG6pLU62IzS7o040IpwCwB2dnGGYFjw9aTmTA75oLG7gLwwqfFKD2z+YGmvjuz74wzIqB28eMkMeC6aDG0XtdJzUR5Qvk8Lj060arZyQMAV8Z1QFsTT3Vto1K7UrgQgvRMmvkqlLjabNB2PueRoTZA9podlU6s2igdIS3MHdBwLkcdKxTIaqNmzwqk+etPbHYNhLBO3lAJqpEbz15eDOm9iYQ+3Rz1n0fHUB6McPoGTYOL3x4wYHCDItwdgPdZR2rOiPfU/zEK0N8bU4giJEWsOFVipNw5Iv/9dY/hAgbgrhRw3EC+Oc3Toxaux/RL3PBxlyGXheLLEA6fiAvNS1OOIvCtgg0L7Qpn1CNNPiUBO5ba+JmW9o4mOvk3dcM0C+1Q6KcYDTHrHF6NZ8Tewvu+HEHRrQC1oaLMFnESPxn5xoZQdvd+EkWwKgLrdnC+MLqkCTvbiqPelPy/nQhVmoJMZ530TPKbumOJ99NjGJKxLiUVw2vPAWH3sE4DqlSpFOs48Z4JytpFqzGw8oleMxvas+EZ1WdHWBLzwAvpHtCGeWREmqVhRt5oolCXV8KklnCpoJQ==
  template:
    metadata:
      creationTimestamp: null
      name: transmission-secrets
      namespace: mediaserver
    type: Opaque
