---
# Default device and mount points
lvm_ai_device: "/dev/sdb"
lvm_ai_vg: "vg_ai"
lvm_ai_lvs:
  - { name: "lv_models", size: "200G", mount: "/data/models" }
  - { name: "lv_vector", size: "10G", mount: "/data/vector" }
lvm_ai_fs_type: "ext4"
