#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: "longhorn-config"
#  namespace: argocd
#spec:
#  project: "tooling"
#  source:
#    repoURL: "https://github.com/enrico-laboratory/homelabV2"
#    targetRevision: HEAD
#    path: "k8s/tooling/longhorn"
#  destination:
#    server: https://kubernetes.default.svc
#    namespace: "longhorn-system"
#  syncPolicy:
#    automated:
#      selfHeal: true
