apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia
  namespace: argocd 
spec:
  project: tooling

  source:
    repoURL: https://nvidia.github.io/k8s-device-plugin
    chart: nvidia-device-plugin
    targetRevision: 0.18.0
    helm:
      releaseName: nvidia-device-plugin
      values: |
        migStrategy: "none"
        failOnInitError: true
        nvidiaDriverRoot: "/"
        deviceListStrategy: envvar
        deviceIDStrategy: uuid
        gfd:
          enabled: true
#        nodeSelector:
#        # It needs a label added to a node  kubectl label nodes k3s-113 gpu=true
#          gpu: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: nvidia-device-plugin

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
