apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia
  namespace: argocd 
spec:
  project: tooling

  source:
    repoURL: https://nvidia.github.io/k8s-device-plugin
    chart: nvidia-device-plugin
    targetRevision: 0.18.0
    helm:
      releaseName: nvidia-device-plugin

  destination:
    server: https://kubernetes.default.svc
    namespace: nvidia-device-plugin

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
