apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-gpu-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.ngc.nvidia.com/nvidia
    chart: gpu-operator
    targetRevision: v24.9.0
    helm:
      releaseName: nvidia-gpu-operator
      values: |
        gfd:
          enabled: "true"
        dcgmExporter:
          enabled: "true"
        driver:
          enabled: "true"
        nfd:
          enabled: "false"
        toolkit:
          enabled: "false"
          installDir: "/usr/bin"
          env:
            - name: RUNTIME_PATH
              value: "/usr/bin/nvidia-container-runtime"
            - name: CONTAINERD_RUNTIME_CLASS
              value: "nvidia"
            - name: CONTAINERD_SOCKET
              value: "/run/k3s/containerd/containerd.sock"
            - name: CONTAINERD_CONFIG
              value: "/var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl"
  destination:
    server: https://kubernetes.default.svc
    namespace: gpu-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
