#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: nvidia-gpu-operator
#  namespace: argocd
#  finalizers:
#    - resources-finalizer.argocd.argoproj.io
#spec:
#  project: default
#  source:
#    repoURL: https://helm.ngc.nvidia.com/nvidia
#    chart: gpu-operator
#    targetRevision: v24.9.0
#    helm:
#      releaseName: nvidia-gpu-operator
#      values: |
#        operator:
#          defaultRuntime: containerd
#
#        driver:
#          enabled: false
#
#        toolkit:
#          enabled: true
#          env:
#            - name: CONTAINERD_CONFIG
#              value: "/var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl"
#            - name: CONTAINERD_SOCKET
#              value: "/run/k3s/containerd/containerd.sock"
#            - name: CONTAINERD_RUNTIME_CLASS
#              value: "nvidia"
#            - name: CONTAINERD_SET_AS_DEFAULT
#              value: "false"
#
#        devicePlugin:
#          enabled: true
#
#        dcgmExporter:
#          enabled: true
#
#        gfd:
#          enabled: true
#
#        migManager:
#          enabled: true
#
#        nodeStatusExporter:
#          enabled: false
#
#        gds:
#          enabled: false
#
#        vgpuManager:
#          enabled: false
#
#        vgpuDeviceManager:
#          enabled: false
#
#        sandboxWorkloads:
#          enabled: false
#
#        vfioManager:
#          enabled: false
#
#        nfd:
#          enabled: false
#  destination:
#    server: https://kubernetes.default.svc
#    namespace: gpu-operator
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#    syncOptions:
#      - CreateNamespace=true
