---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: proxmox-csi-config
  namespace: default
spec:
  encryptedData:
    config.yaml: AgCtFFa+8OVhvSh7j/L1Rg10VFCk/A3d079Hh4kAPdRFHAQXEbxm96cIcGaiuztrG50dubaD9+/4hqDoqBYXuExbJ3fDUULmWOGcPZ/oJJC1l2MX0o0ybN3u1cclg4dan7mubfSI8rBbxxJGB4qRE9VjB71DdS35u2Ju+rTSg3vFB/zOTkH41IacALq/iSluHtsjdbnuiUEgDBEwNh5ozm7edwDZwxX3euEvPt97rgjOx6HAPpUMr43l6vb5DdFjPyuZOeSvMdMG/ckWbJtKUYdYpvVkOd4Reytb5aRlflngxjnioDzlMojT0DvHvoYbALR/i/1KbJcJXCt4Z6LzyigJv9yfqcskp0xLDygUFONxOhBwdMmiNIZgQh2DTD8inGA1UHje76WBmLRn8CaPFV4V43uLHgG4zXIj4pDNnprY+70Yyn/HKqf+2thYPlLd8WR72CaJy2K9dWsKFTGE/LxDas6NIA6Q2C4ruD3MxojMKC/keDQD7e4fyJ3KstmXqgFHB/wptav+V7+UsnLdyuW2+/9Jf7K/xX4c2KKL8acIIroy5a1J3X7D+R41dto72z+juSixgmx6XqNMeOvFYgVNDq8/pKwzBUwZKPjh3kjx7YJAo95svKjiB8W2MnamFe2sUtwExgi8fEPnbJxrZczRirmUzDE0mIvYZUc84JGsDdpzCfRzHBy0u7CzlAguf52mtTaFVQY7CjSwDqEbDlwmGlhlJBh2lunOGN/+SfnRRW/bgdc5UvVEuCIDvafh2UR4HripZWl/P0BgMEjjWvc0XXeXSIQWEIefGdov5NRHh9XxY2cU5yQwayfeNqclBeo0FpjEl+GwNOcgGEKZamU6Aot0zj4YEyRt3svPWX1qg9o2OeC+srOwAFLdxtGmwsa8syVLlOgcbEFS23HI66GPcVy4WzmDs6y/kblr7hotof3LncmdBayQ6eKWPa65TSTS4zr+8M+iOhuWFSRIKX4=
  template:
    metadata:
      creationTimestamp: null
      name: proxmox-csi-config
      namespace: default
