#---
#apiVersion: bitnami.com/v1alpha1
#kind: SealedSecret
#metadata:
#  creationTimestamp: null
#  name: proxmox-csi-config
#  namespace: proxmox-csi
#spec:
#  encryptedData:
#    config.yaml: AgCMTJPwcI1A4tLjHZvi9+t5Cq9XAp6v4+8VHI+QMPqLfd0yyaJ47R0AqGaQYlkeA8BrYGQuqKmMHGvD6PMZK2EB2zL7UZuL0XCwJVD9gRssM9R2hKZol0xodtZ1KBerE0Qdfe02eMC93OofKID2QFfjwOc+PfxLTiXpozGOIHxjJGp4gfqbCGryuz/1vJ91RTtV/N8W7zF1rujxsMfQmQ2ENSw41Tspzys8ylKrbkkW3YCVaDj5GlzrB+Gd3K7hhi9z4kWR3BogvIN5aJ0SlzhB9IfN/oipdWpkaXoIF0VP8Lpp9r8HYMu4hETihroTNH6BGVM2iLZIxOWnR1fQJZrDGPwRxwQNdYic9YOqu/JkymnW/WsdTxum7v8ovlMY+civmY/u3gividdo3V0ECPABzZ7W0bdNJDwx/+oGyd+bIzOmA0qzMI+1fK0VLTUEmnOXwhwS+QrLLB/2LHGTly5eSE31dhbKqKdY9SrHuuvcs3Qro2CHdeJjdu6tDo/ezI/QDR+q3s5dLfYN1knsZBmZqD6Lg6Uwlu6myxlCPk5nK7OZ/Wr+wViWKFaLBWdnRawMwK95hBcneS0DPmNJ35FLAErkzomdGDjVco7+NbPShX0Ipg9cYn+u6KL12n/5juimdlJiuJWAJiDcsjt1NuZUVpudpu6dBad4zk5kWyoW1REao3mlXde0ZC0r29peSK0t/x92uEuwbuBzu6mE3aq8AgelE4pYIWdVmaTlyff5fyjBl2jw1oYzG22hW11idWdk/xnZx3qPwbQY2QzIqQ1PO4YmtJ/FPKKanDedndDWAbOBz0DSfYD7hhJn7qh9T14OQdWXhVJ1UL+nAAHb8jefs6Dk0/0O4NxCbBpmqvr0DQJYxxAdh/2gc0xPwT9BakeonCr0mRpZwMJeA5v3MwyzQOTQm8DSD840n3908QReucbGCWDpxee5N/jCxtYwA7l1CMCODr1dSellPgDkCgw=
#  template:
#    metadata:
#      creationTimestamp: null
#      name: proxmox-csi-config
#      namespace: proxmox-csi
