apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proxmox-csi-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tooling
  source:
    repoURL: "https://github.com/enrico-laboratory/homelabV2"
    targetRevision: HEAD
    path: k8s/tooling/csi-config/
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: csi-proxmox
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
