---
- name: update-initramfs
  command: update-initramfs -u

- name: update-grub
  command: update-grub
  notify: reboot-hypervisor

- name: reboot-hypervisor
  reboot:
    msg: "Rebooting Hypervisor to apply IOMMU and VFIO settings"
