apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qdrant
  namespace: argocd
spec:
  project: tooling
  source:
    chart: qdrant
    repoURL: https://qdrant.github.io/qdrant-helm
    targetRevision: 1.16.3
    helm:
      values: |
        persistence:
          enabled: true
          storageClassName: "proxmox-zfs-nvme"
          size: 30Gi

        service:
          type: NodePort
          nodePort: 30333

        config:
          service:
            api_key: "a1b2c3d4e5f67890abcdef1234567890"
      
        config:
          service:
            enable_tls: false

        ingress:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
