apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rag
  namespace: argocd
spec:
  project: ai
  source:
    repoURL: 'git@github.com:enrico-laboratory/homelabPrivate.git'
    targetRevision: HEAD
    path: k8s/apps-configs/rag
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
