- name: Configure OPS
  hosts: ai
  become: true
  vars:
    packages_to_install:
      - "nfs-common"
    # mount nfs
    owner: "{{ main_user }}"
    nfs_mounts:
      - src: "192.168.100.62:/mnt/tank/media/library/books"
        path: "/data/nfs/books"
        fstype: "nfs"
        opts: "defaults"
    # Install Docker
    docker_users:
      - "{{ main_user }}"
  roles:
    - packages_install
    - ai_volumes
    - nfs_mount
    - geerlingguy.docker
    - nvidia_container_install
    - prometheus.prometheus.node_exporter
