---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: navidrome-secrets
  namespace: mediaserver
spec:
  encryptedData:
    lastFmApiKey: AgABfYaFG7llYU6mUHRzfDyvHRZlXLMIHaJY+/VZ7OOy/t3F6o0CnFQiRr9cHBOQCxRUo1tiRwBKR6dOrKmUct2sGgo0FAan8llLwtf+A1FkQC7WSx92QZtzJfnfZUt/UmCnO0qw5ZVf+tOOmtWZ35MsMCnX+Na8moDigVQYqEUTnehel+Z5fOY5NPZj1OaCSmnw739BFmvITVJTX8rgKEqmmIb7hASezTCRCUCkoNEmHTYOj9IRaSEUVT+6/PS81iitFTxikFuw1xrT3iZN9k5nHdvMtvVIo4c+aX99VmJCxeuYXdWnTzNWCxlbBik2y9xMtsFOqZvk/aHVT3kWjNiw7d8iGhIPuiTTACdyRNdc0uzRK2dODdxSzw7eJ5Fzvk4D9AjEAdZiSs4vFHaP53wVxZnCLf1Uz5plDUr3I6cskjtyuYTFxXlLxqIncKyxpcGF9nsb4u+1yLb+NW8ErkNm7awkx+C73JLQRnfWwa4hNjJWb9TYQDnYya/uuTVy4g5Nc/+Kz4KbGx7zdNBZE8ZQrwk1/tfPaMQanL+Wycbt44EidaNugq+FJi/j+w/8W4Dfve1XwERZd1WHYc6w6DqsCS/YNYboPWbtdMh/Ln4XM92w9Iedr+Ksh3AGdtQ1DCsefW/UhnAH/q41KILi5TpaEJKVZu2ngI85pacqQtgh/BVxKPh6ao4FyQilWhMRgdpPTlVBgKwhvRKJupcxvvU4dZ3Ff1Uw+/eNxz9IQ1dFVQ==
    lastFmApiSecret: AgDKS56Jw809GO58c2cuC2albDCdG+Ol8spW9HRS9Qvaev8FOQvmXmoUmF8XE0TFPeaVA70rzAzORxaz7wTOhdHS6yPSo/5+5sGcxmdpE6TVf0sTYsz9vW0ljOZijuwy3Fn0VHJMIFkHlTbnOqFcTQISw7VjFnS8qVLlISaJEZj1dp2kFCoK7WVojVY1Rcp3a7qWnf1im872XPyMZNyGQghn16m1qvUgJitB4QoYf6QSuIXIKP2CT1eVyIs7LqHL4MUX1b4u/+2B1Z7Rp/jK1nn2Bulkm7SJczMw6zpim9eSEyKeQdsgZchewK/gIZB0No6yg4sQEDR/CHMfHXNBMpd/U72u3sTA5G5tDFqDb2hxGLyqBRFSS9OgW4VCJ6gWgiHx4Fc81edBAu2xsjTzUbmxVQ8YZFJqRyIMG7Gx0POD961GT9r5A/bnlfSy1YsUo4Uzp//izrgAUy9QNqaQuJOaNGnvX1fWwo4xaHpCZMSMt9VZDCoom1oKyCF/k80GOywh/IwKXluKDimyZHGj8zEfrvvjijHHavIcLnG7RUuaWBcfxCK8v6TI+bTn40WwS0c/lzT9mgIcGQk0G+wzIIb/SM8PdKpyaSbj9xVdRdTRpRq57jH88lvTImIEJ454nUiiN/6Opl+oRcBUMJKyJPuchk7vqltYuNt1tE6qUcD0TQmOxJKJ7afHlgLwK5CRdBXq7vMrhX65MzT69cxvGFdu5dvwj0ShvDUszaK5fkjWaw==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: navidrome
      name: navidrome-secrets
      namespace: mediaserver
    type: Opaque
