---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: navidrome-secrets
  namespace: mediaserver
spec:
  encryptedData:
    lastFmApiKey: AgB/uC+tmDr8I5dSPrBTfkpICcT9g0MqyzlYZSuQFurGZAMhFd+W0jU1tUvkDnL4bLdf/XpZ9tpxxpZzwKWIoRmBiqcOIpU+cdu/iPB/vledp98befsqYXWTVKDoDfYwqucYLCDxFFcV5gPygs9FGFiZfOc5wWRuqcShqiR7Y0/dsF3JMY+1xUEjYXqxFtilfKEmF3b+LDygKvEaGZsC4mTntXiKBDqY/CD68QypDmpqKNqqCgGsuczrAoodADJ8CuCPcqeJmLcpKlSC42hMVX2Dem9DG+MLJNioabu6D4RuKrWUGvS5wZEPciji3NRuWHgiGQnttzHnO595xX99PZKDptrk+FVrusWbdcqMFbKNv/VuLh0G0ZRhKtVjyW7k5E7d6S7gNJ4bseTtkeSWk/fxW1Gaot3imOcwL4OWoErwgk8PFnIk/WrZOHz9AGnJUqKF32vwspE00qdjzGiEmjM8o59nsgI+uqg5+9LxqMm7qPsVm8B8kEVIxKJim0dSlWuxzIRs9a+6EIsW+cpo9GG/J8RLj1qVRPBbhmHM2uZvAdbvLfr6s7qO1TRmHJckTLKWiKhYRuzWBMJmLsHGVolU/N8PRFGeeNi/N0HxNOTial9NbRtBmHmBXzW7RoU2Zff0fQ2Wc1HJc6V27Jqhz+BqwYO3IekE2GMNecNRyH0bHlHA1xHae9nRN19wHvOu/8cOPLTEv56VuV6ZsDS9Ier4E4T22cyRrXGYSy46UBRqyQ==
    lastFmApiSecret: AgCvdZpYDhy7OarCrijImkz2W7odCn9sFDnA0sEksjfJRFy5tpFCtIrI06Wr2wccIIQNQsxAMyiENb6e/ihsZ5N9IjQ8zEBGmu6nBN3VkBuVmQ5kWxA2Mq/BKo/qCdn5tQeXKzkz+CItZYJHRqNF8dJUzZHXSzPjmqvOYUrzq2mVLO+JpSKXlgFMvIvZx6BUWppV+jEtbxZBahZfbSFAFcgapxDURszJO3O9AGKgA6rchty80EczinsDWWThXJmeZunOYDMfYn6mBtcEGuGx3R2FvyHeWBclFz9142xV0HRwgIPwZK8Pr32LVC8VawEpUoSC6EgWbn7K114+RGCUh9dcTdrYWklrC5HhHe/f3b+honAS1WzsXssXpzAIf4ifFKRE3WZKy+sjXDzHnzg4a0ku7OdDpZ+t2TPMI1t6itZtdEcN25EiVzLM82QK3JvOMWLmehD6DdFJu5Dqz002rZYRyh9/CxbfE9b8TPw79Y00VlLQsb4Ks/S5/Ne3tj+45hPSBCI9Q3rKor6+/y5CO+vAnSzHm/7HNdYPsJTrhbXu1X/FP+qM8gu4j7yHHj8pE8ouBt3z36B4ub2YdAH19/Jsy0Yx7ap4GbKZ6k+PqTp7MquLh01pFXT+enXTdLmK7MNBD8nXBQn4YKTLnPGC1F6vKKvEPNX3pZWK4bo3iKaTRS37UD7No21Ptodotvi+eOlMrXjlT4EK4bSXDeeInke8PEoc2drNg2Ra9AX3awxAyg==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: navidrome
      name: navidrome-secrets
      namespace: mediaserver
    type: Opaque
