---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: navidrome-secrets
  namespace: mediaserver
spec:
  encryptedData:
    lastFmApiKey: AgCZSjVU2RLN91djGc5EhnPIh2Eg3eh2LSyw5wsHh7bIGzjo4eA2kxgdSZUQUnlePbdluGJoQqOHMa4wkWW6pfByP9kK62qUMP40ZYws9SKSZfY4In6rn7YMbv5EBBtD5/wyxAK14pZOAlDhd4WspiZN2t3E6gJboD4XnQzeVyArt3M0OEwOEeMgdkeCnf0IDvOJhf+h3dRv1X7jmHoKB55Bn+XWshw/8VBPbFwHEL6z0uu5UeEp15g3V0YGlATDVzIXuYQhazyTKQ7bnEjdHaGl7g6K8yVM4HGMCyDZQZOev2HcYoOJFp7m39HAuJyI1bmwNlZMJ+Q17LdIM33JwfnNRfyBHlOqoZW+ijp/AWwYOjmMbc/u1pitqhgad54j9lni4OTdg8beG7SfBpIQfqDv692OdJ+6oI1DyKHiJRrjlSdVi+l9mkfBhjidIWs0LU5KjkR7idMYIpIKSDCv/F9OnVt1v+IvyMS4K1S9YfxnxdauFzxw2+vMXRnRaTzIoFNV1YyHruwvX27Q+PBkaLMj/J3E9C9epr574lIJmN3b6nCmNJXe6weO3DZ7VPq9nwtYB37ThqyB0XJBpYe5dSGNsFoD3JZrJqedQ5QT5WeRev5sf4kPV1w6EacGFujHiI64pbSliM7WKtq7bUjOJOVRUoMlokTSGn9cVVPnownXTx5qK1XIScUOJenMYg9ndVH0rEidVKKWg+VcC/uA9YYFDflfUmo0fDiqUCp9Zds1ig==
    lastFmApiSecret: AgAf/XC8uIdpFtImyZ843nPAHWrdXhmaffDPI+p7moQvwe3CUhi4cWA9Gbsw6k1BlsbA2u/6/6sKd658tZ5UbvG6Ucd61/ndGn6nnBMv6BwQ/m0Njd4OfsHHB6v6XLW219Bvw2V13vb0Vkf4R5znKi2all0sK8apCuUD5IFP9tHyG1514cxki0Rf2LpA+cDAVLAuZftj3ziAetDIeNdG7vECBTkfPpnpgQnNK2q9VEcdfFXUe6ri20Btefg+mRgSyu6maEoFwGORQ4jIyQMTXxPubWiImR4z0Nzb6+zik3ygtjFYl3G0wkn7Ta8fahOayF4PCs+tv/z7R3gDTGrPlw81y89bkHUSNQvLqEgExAK9N0DXZvPkCwXZYhjWI3h6NFXQcIAS+2QyjvnrLCxs1T5HoOq2G1Y2qTRpdCA0C3t/c7y/wEOm6L/jmYEAO1Ydh9RjQS3QWRS2/Ohc2i+MQ/8rcfR26IF5Zbkm5A+FvywZZ3gdeNLQ+QWZRviPaNgPpZKrUh7A7Z4H6gIm6Q+/7H2eVkwZLlNZeJSPWdpNe8ArD+FUiSJI6Kbqo7+1gVed95yiv4oRj2Nmrb5cqBTlwK0nI9ZvkfC+osrXf8TesUJChu6381bv1MqnEtiQ101J4r9GeKk8lOlV9yBtH82kbuJg8PDGkNv+B4Hc3mRYwAKXcDyN+vblfn5BC7urqBNE5ME9mccKwGZFgjn6aulFFVC/ITt7BhBcYXebXex+iDABSA==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: navidrome
      name: navidrome-secrets
      namespace: mediaserver
    type: Opaque
