---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: telegram-bot-token-secret
  namespace: tooling
spec:
  encryptedData:
    token: AgCRZpuMKCt5zb/On6Txb8a4QIb0Ab60FezA1aepZEvq433ki2pYxaTRZa/vS3J4ll0rM4l2vRQdylDJMsQWO30mbv71dVzf4sYiJxkArDA0EQ5Si/YAEIvbuwEcjYEOYNzlw+gEfLiPTjv48RX98NMUT/FnOmDZRg5kXSOiziV1xTPfrewEMk3qhl+oBfX7Jax7EyrhUI3L+fB0lKHlb78JH9AtCku0qLtk7QIDHlQiFsJ8v8dUYliJKQTfqqRWbIILE50xgmBR/xHMrTyOX53dG73ObS/3+GNWLEvAYQq7eIVliWCUNv3C3PrC6XDsapqvHFmtlWqeBlGvw7fcyY3ZkvGDzEZm13QvDxeU4MA2mB4FZ46K+9aca8FFr9gHn3nDEeQKSaxtCx7vOGIjZ9au+HD6lXrF7+dULjbRcHOg7feyH+jyd7nPyLRcCQhtZu+LVnT04jRA1wHaIAarjXvTMjc3xsfY8YOHi8Qf0/CMB8cZFXqMoBT/NjN6VIZkF6MF3PdE0dr/+VU6B+lzAPxaQWzFwra0UDTVrvH+KG4cI/7IxqiYxR6sKfC2riLhZ3N6+0z0SewQcIi9FRC0RB8U4PVBxxQqETB/a3KEaS3prQcM5sA/6JhLPLmE4jR3dHa4Cz5VoAV04gHrTapGVk47o4vckdly75zOijAOTLunP1INW2R525BcBQHAaqwpYrV8pijsM184WJAMne6DcVWWIag8DMCIdK+Nl8N8Fve5WEuSd3ZMufKc3myucQL7
  template:
    metadata:
      creationTimestamp: null
      name: telegram-bot-token-secret
      namespace: tooling
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prometheus-grafana-admin-credentials
  namespace: tooling
spec:
  encryptedData:
    admin-password: AgBroLgSX80JvASLuGmdcub17Em0058ASDDZ6aHxCXpDvgcpi5pv1z6VsXiPGYMyGT5sp4QfypDMxM2zBXxUGa4+f5taiydWrAojJIe2KdVHRYVNFOJkzFnsYyqYwaK6D5Pk9Iqdmcr90crVJZxnV7MMBgrySnGPUp96VKBUoOiBSs8Auj0kY/YSlMP3SP9rj4IurHZW0zDWDZiyMLcVSn/k7SiSlZ2nLPcmg+Ib5Ax8pgILxp6zB/1RlLloUVINjJ1QoPdMi3XOphwOf7ZsH73ONc3SIXDX3kyPJtmQf90lUYe7eMHmy0RFje6iMn7i61svzAs90zx2tSFDUrsZNEYscl1CUm4wTisqcwc0hGHLch2GVWbIRERkET1j8ki+sV+ePu6M/WN4Ho+gUpRQTGlJVYOQdgBdGtbyD89WSqWdtM4lx5AOLfgnznQqdKvIwx2bC43ua8nPzYRtcPse1WGwTNg09hG9C2fC0PKJZfLmH2C9eiES0o4IpY69I9lseFjTJk5X/2VPSXotZETJOfE2BP0eKkI6NIzWjp97SmBspjNySVpy7LrFKRILNxFoN3+0hFto73T1T2TE2qmbj/oRZYflMs2rUx+/imt4vOnM7SKYDt/hOvrPUTSuQqNdh4ESOT1aWZ+QJEd4whg8YwMQudqHJhha40+fieI5KderYSbZXIDKY1xbP38lPYol2biAv4fRIlBWwpyEUw==
    admin-user: AgAo+2k+YKp6s1p9ViekHDfbpfUuWaFHTJkMc0L6dWh9pvj9Nalb54ZVPqA9eBdL5BmKPWPWLQnsWMl791e3zH1JMavfIZCMHYlSxb7c8lRDUMMhSvOixWwkeuxoqEQcvVHEjTBMxmgYysdTrG59kQegZPf5HOmrInvHT8XaQGkX/7/vWZe7GexxTHUBl50X4nAjZi+L5Esdda6V8z/9gaIDFxYDqECEuQwlIPfycudfICGP1i8q/ebv+zwLgwsfrjLvOL1nAveWbVfziq1y6mmR+1X3X/WZ+gd7FcKzywStWD64gKssUnBbCeE3r/L/LYuGWqs6iZ56idyBzryBk79IxlgYYi1l02lDlrNe/8YjuX6jlt91INmLeKNPB9Q25bOd0Xx4ibNGC/U8CcdbdHigAzFadzKjvmgIhgrSUgBo1G2ZRbHOKt4GjcNBDf7oanL9rgHmVms3YeR/OepL6+r+dl/EPGr++aYzk+BIk4mF85pUL5yrH8A/yBdqeer/L2Ds9OL4ZhNHH+DNfRMyoVmkDCauw9HC7VB6QR13iD5ASulCK6tEehqQcvf4KPUQkPaTMdcpnQVRSNjxoLuo/VLtjbUFcRIX1cV7wRK5Ayjv7YHlTpto0HIpR+2QBEZnxxKvT89pA7pbE09POjt0TVIYwUwLkww0NMmXuQgV90/xTGR9cSblQ47MdRbHfTY6na5D0DZX0g==
  template:
    metadata:
      creationTimestamp: null
      name: prometheus-grafana-admin-credentials
      namespace: tooling
    type: Opaque
