---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: telegram-bot-token-secret
  namespace: tooling
spec:
  encryptedData:
    token: AgCi+Vmd+RXM5p/495+14KGIO/m47yfag+ci5bj95g3VQkoCh8RA7xY9ACRsfgDech9NZKn4jVT4L5tMhS7lFC6aZC22K++PicKbnZrtEgIrLOKsSU4IbhcIsxAyEY5qz8Zuh2upqwOd1ExdsiYBGKYmiiYxSXRxPsuWpE6qSR8IdkdBrbwPCc9CizBaBYNY5ZjCPubwCp2IYF1jg2SQWlXUUhn2dTPdURix5jL1DuEG53Q7iVitaFqMgZSve8p7Ugm8yYNeeOL57sX8xzzvCQTSZ3FglgJmV+tifvzQX6zURDCcQNilNiFaevln152olGoSTCWd2qodHWcIrrFg93dKRZhJ8cCKrFY9vVroVxKVzZNKo/e439/JaWWOFnLI63bTBn6yhOhtjWlLR0Vc3R16F5D56XUztc3OOxwDpQfaslMdcilj0mJbVw0/8jVHGKozbcM/wS0LpA2HTVdDtJQrVppimLvD9PyJXJhB2ZdZUm8LaPbI27LL7B3FuviUGffKh3n5XdYNcTt86SUW8RuBW5HPLuwZoV/vLcTQmToIGWru/DXBrI4tvK6sHb2YAPe25k/KsPBLkuG912YiCxg7w2AhaKLuTI4xBrCyNSo0Vzotg7F5cGa5iyxZ3Q7BJVjGjDLl+Pka/yc7CGxb5izpxZzIIFWudIBywlgril2QknN6zwGcjzUjIR36wHNW3Kvc4PIu8IUEd4bt5JscOOtfT1MTHjNGhr9yrGLf8o0xfaUaK87SbbQSdaK5jmD7
  template:
    metadata:
      creationTimestamp: null
      name: telegram-bot-token-secret
      namespace: tooling
    type: Opaque
