---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: telegram-bot-token-secret
  namespace: tooling
spec:
  encryptedData:
    token: AgAhz9XyHC8EqWmyAYjtsCX5dPk23ULzDQ9Zcs2o9J9q3YIK1OKKhtJ2PkIyvqtYE7ZJXFz9o4hV/jayW8yrSNMHl/l7C5ZYxYgmWkXLfIVjBeqOvLtyy4XuCcUnEDpLqvRkNFP4p54Htsrv0rCZMofY1mbROJqyE6sDSSKlyJq6l0GQPXGi7KkFH9Opw5A+Ltj7MiXrhnKjnwht/lcltiL9GxM7Wznwky4/QS81oSzhpamddisMXJE6FlKbyeeN2512UuK6LPojfS0TSq5kvCWOYtOdCdXR/2hPXlFkkSHkrga26Kxd6dHMTbrsXV97Uqmy6GIgzlb3uGjeXBfQFZOvjwd/P8M212bqvkearQAd/WKzKPlKUXUBqllMR1pMCj4fkTu1pewjrlUCDFaVavBCs8GE2E7VbyOhojtEbMIfTXIVade4ztFSOu+jG9XXyYkPrhPN1V/+FhMUpieZ14hjyYRHWEOIMwUzhP8w00e/qdul1Qkt2cEhZ4ZghWpdiIW0+954/wTiZCTGnHozFpRPIVVM4kljVUilmivAyDhyAqxrIreIQ6E7kB7XyXE2E1vfEWiOSwfPr7yEz03utptszz63ydVQIHwKjW/QoypNrr9VLR8LOO4GLOX8WcJoH7c7P8+S+M8S1RVg85p5jdy4pZxplqDNm8rOoGrOZy0Pt29G9mhJh3LSGSesitWd5cxSFempFddsA1a/dlo1oS49WmXFtBhNk55wr2GygCO4Uz3KOfXpH31HBRRd5u5w
  template:
    metadata:
      creationTimestamp: null
      name: telegram-bot-token-secret
      namespace: tooling
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prometheus-grafana-admin-credentials
  namespace: tooling
spec:
  encryptedData:
    admin-password: AgAFX+ubj1esWpOT17JTcHjj3Kl6Vx1ZF/eNFZRkWkejv+UZkSAQ968/nDrfseYICV4hGm41GuJuoNr4ku8cZ+Z2J5VYEuLaiSGVz55PiB0wGYog7io+H65BONzGXJIFVvXrl4wlfsW5MSurUcNoUM4yf3fXebowaK7zLEldRJ30k/wJvGi7Z356LZsmm6QGcvgbfViyaOusxEibOB6P3Gc2y4pS/eKWiryPiIOdfkv7xkGAnPNLN5Ss83mYGScI4Pkc14WWM1h6cL2qUKLJRH9FDvSoa33EurPnvq9Okkh4Zxn5ZnFVi3EammIY5t1RN+NeQ9e6e23m3iLYcTaROA67eLOvG9FflcIz0sQhvIhoe8XijRZgWkFvp4TLYq6F/3T5ii8sJcQP+wJ02I62x5IFZ5Oi7OAattL+v8ZiSsBtAhX2AhhhRCFwwi8UX/tyQF8mP2yt6lMB0Qdj3FY9Jo8j9tv/zfnPwCdwM2cYzaksNpA9WSRvjDb+OI0IoTHv6VVy350X3uFGpwwAOxmNMJoZ0U77Q95LgU/B4WiiFljSRv991F/tiLJqd6phYaeG9DybPbKy/13ktvXIzLz3NVsS/3KnCsYDQMYDPtw7iR+yi4MCIecUreB/t866w0+/zbg3EX31iVHxMRWZ3GX0bIqVFHNDIqeZH19ynUVN7uEu2LY1xyrSV5RubSGARnJnDOwSJBC0kEl/olCxDA==
    admin-user: AgBRW7b2ta9FKNK/ysNMKAQ+OepjwbYOgz0G435L8l8layeYdYe1/Tw3g4DCO5y1OYHGsF/Q5fBVoiDlcCdNnL3WXSVTBH2R93m0akFE/XvbLiuM0JW2YwOpXtKML3pfCWxnOEf6gFyDxbQ30h/ZNGxqU6h/L3wNSy4MYJokJ50vHvTZHcW/4tmIUSsJQx2lWFeI4ViofGXcRh6p/NY2LYerw9lfeDfCgTudZmqjC6nogSt5MW6DsOwdrQoyHUhOLM5xXgk6kx4T89MRtebGAvyzrU1Gllybm72gDPv6JGf/4rWP4kjXUnrdnQpTjcI+vuqIiSgdNH2J7KUXE7IGG4fe+fTQea/xCfu0EdUKhg1NQ5TGflzAePBFvX84qGkDuz9ZPwH6DAXxuwSTYyZVWVL1OyALvxz5Uk7PKEB4z+0MgvYipIyj9cX8Ogg3U7CAxUmqUqEd1RTCwo2Hm8PpEqWEmABe2OMmjb9WU7eQV4Wxwv+NCt8Z9ot2gSNNIqJehM5zdY8VAB4+eSPIgEfBJmzGrKtVAZ4oZWE9htMBUkHAbHni2/KWR+SDQSo5rKMaVCtLb/fIPEynjB2D1nCPk8QCJ17YHOe4k9oUAmLfkJYh21zPg1UqgedMpvRj8GLjqbx4Z9qlUG4SjPShjQ4lmHzOntIWCo5zPclum1gdI17DMwJLide/RAaNwMrrbihUxUmSPY2DzQ==
  template:
    metadata:
      creationTimestamp: null
      name: prometheus-grafana-admin-credentials
      namespace: tooling
    type: Opaque
