- name: Install sanoid package
  ansible.builtin.apt:
    name: sanoid
    state: present

- name: Create sanoid configuration directory
  ansible.builtin.file:
    dest: /etc/sanoid
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Deploy sanoid.conf from template
  ansible.builtin.template:
    src: sanoid.conf.j2
    dest: /etc/sanoid/sanoid.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart sanoid timer

- name: Ensure Sanoid timer is running
  ansible.builtin.systemd:
    name: sanoid.timer
    enabled: yes
    state: started
