telegram_chat_id: ENC[AES256_GCM,data:QchQ1Vo9kcb4ig==,iv:Xs472itdQXJSNJ8kfhdEMWzKBqP9+ConInXE4JYr4Dw=,tag:g2ovWpYtKPOX9F+67Nz/JA==,type:str]
telegram_bot_token: ENC[AES256_GCM,data:EyUv6kCPHg+Dvu1voiWI6JJRAwkOTtT0S9tfCq5mP5KYdGDDqfaBO7DdGf9sag==,iv:S2S8ZehbXwxDiFFLy9ywUWDoQdwSSAAEHDGkE/8xdvk=,tag:aB7ZcZZPuLbns8oXxtlS4A==,type:str]
main_user: ENC[AES256_GCM,data:tq79OMZdQzkc,iv:mlVAMDvy4vks5zrKCxY/UbL3UQRvd3fRrBy63WOtegM=,tag:EROqJMDgCJp4GRDcvAtslw==,type:str]
search_domain: ENC[AES256_GCM,data:e+dqQdxitK9AjAGQS/IxVLIt,iv:XsFW2D8JzQmSmgh+RpMv+0AUKJ+VlKD7nzY0SsQPLrE=,tag:zYpXBO6NUXEWj8ZS76Y43w==,type:str]
taiscale_auth_token: ENC[AES256_GCM,data:fKoTnY7jRw5+vvLmN/HTmkvlP1o9zmeMWj+tnyfvtJo5pOi7F+NPgQhRcpi/9/YuRqy9/sxSZLHWhANk9Q==,iv:gCwvnfWevfXAvrMIg8KMCt/zyWAzoRv1RZZ3a3YK2bc=,tag:OJ0XmSHPjfSW61M2kYsugw==,type:str]
sops:
    age:
        - recipient: age1gdp9htuaff9js8n4vl5y2z9nq39cctn9v2dae2v98hfh5fxs23cscu987d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZHhiQko3Z01aSXpxNlAv
            RXRaQ054MEROQVZhNnNUeFZMRTB0RU9yK1ZvCnVsMDQ1UGZmWHd4aEFUY1NsN2ti
            N2ZmSVJ1d2ltdldNeFQrMXlkUDZoRW8KLS0tIHg2Wm91dXVuazUxYmJMOVFGTUQ4
            dUJCMkhmRUlQUUZyMXpiWU03WXh0aVUKLVCuTkqlLBfOg5xApPqxsrhjKbBt3Wrz
            s/JkrADPPo20xBMuHoThGYR0w3z/1iijxMAFiHiBxfytPr3pssYDaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T17:06:55Z"
    mac: ENC[AES256_GCM,data:tikcSfX9l3iieyOAwVN//0FajZ/CZtjmlPrL4Qye1go/HoRrtDYLQLKKI4znjJ0k4By/LmCNUxt1eBOnUB6+P/is6aVzHzFdMrVTe8YRu6KGkWz0PIZHjQO8EIsrt+A9iApiPEWSqMiPoOvG7ozrRyQVrmdIE4WDDeTZxpwG5ng=,iv:jXLb5n6BGFRDLZA74cCtvyHn82zYNXFvKh4OywAWusU=,tag:X7mkuH+Vp/rtD7xWTgm8GQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
