---
# This Manifest is deployed in the Argocd Application pihole
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-password
  namespace: pihole
spec:
  encryptedData:
    password: AgBbsgn31UinEQf9wgS/pgnTZpmVoBWqezbS8u8nzfsMfXpDiwjIZqPXkWqDHFcWTRNW42JVgNPPTUZwfKhwjiEql+EVzkF0IjO2Pm6cdnPQv2Xvpl6SuWpAVGXDwFjluH+vv8Y+QCMo1BQm/ZvvGtF2ahgCw/g80Yv5GjcqAQ5ntPrthQXEAE0hFaQ9FTQ+N2d/NmOSsKURC/3ilHQwtJkeCHTUXIWcTGWXrBnGOxtyfHUOVXG5y06m8xO/8odax/HZHaQlNTBaex9v4U2yRdiF4PnBQYdZCkwWw4FDtrI0sVEgB8rz1q79hOQ1k5A9XN7N5MG8Acc+7obWi28qPtYb3KUk4G2+pxtThxzv2QqGM/uJqtMmz/kkvgx7ysK2w7lqaSMWc7GQgXZirh8Jh3wKcjkd/5a/OmvIgswDEy5HPxNOG/BVS7D0tv+gJPfvL0pNHhahFZhIQ85oCZpdLnbipr5010EjheEVB0ljtSS6t1wu3J4r+I0suh2GquaJCeZn84nM97A3M+dPonoA+yQpMMwn5CiX1wd1sxPH+AzrQx2zDilTfDbD6zfLEgGhAZCUj5uMkxnKEIN6imKg45dbVj1UPtiwmVQaVTM8gmvfALpy4bM9edocrAma5G7GsTTTybXxhVflTeZOCUTWrfYkhVFp41iPC8ejO/fc7MnY9w7vtgx24HO0VOl/stCllDFXs61hh4x4tdAozf6IeqiuXhYG0Qw=
  template:
    metadata:
      creationTimestamp: null
      name: pihole-password
      namespace: pihole
    type: Opaque
